apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  annotations:
    kubernetes.io/change-cause: {{ .Values.deployment.changeCause }}
  labels:
    tier: database
    project: roboshop
    component: rabbitmq

spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    # This match labels will go and find the pods who contain these labels
    matchLabels:
      tier: database
      project: roboshop
      component: rabbitmq

  # This is a POD definition/template (pod is a subset of replica-set)
  template:
    metadata:
      # POD Labels, these labels will refer in replica-set selector
      labels:
        tier: database
        project: roboshop
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.deployment.image }}:{{ .Values.deployment.imageVersion }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: rabbitmq
